#!/bin/bash
# Claribot sudoers 설정 스크립트
# Claude Code 에이전트가 비밀번호 없이 서비스를 관리할 수 있게 한다.
#
# 사용법: sudo bash deploy/setup-sudoers.sh
# 제거법: sudo rm /etc/sudoers.d/claribot

set -e

if [ "$EUID" -ne 0 ]; then
    echo "Error: sudo로 실행하세요: sudo bash $0"
    exit 1
fi

# 실제 사용자 (sudo 호출자)
REAL_USER="${SUDO_USER:-$(whoami)}"

if [ "$REAL_USER" = "root" ]; then
    echo "Error: 일반 사용자 계정에서 sudo로 실행하세요"
    exit 1
fi

# 명령어 경로 탐지
SYSTEMCTL=$(which systemctl)
CP=$(which cp)
CHMOD=$(which chmod)
MV=$(which mv)
RM=$(which rm)
JOURNALCTL=$(which journalctl)

SUDOERS_FILE="/etc/sudoers.d/claribot"

cat > "$SUDOERS_FILE" << EOF
# Claribot service management - no password required
# Generated by setup-sudoers.sh for user: ${REAL_USER}

${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} daemon-reload
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} start claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} stop claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} restart claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} enable claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} disable claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${SYSTEMCTL} status claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${CP} * /usr/local/bin/claribot
${REAL_USER} ALL=(root) NOPASSWD: ${CP} * /usr/local/bin/clari
${REAL_USER} ALL=(root) NOPASSWD: ${CHMOD} +x /usr/local/bin/claribot
${REAL_USER} ALL=(root) NOPASSWD: ${CHMOD} +x /usr/local/bin/clari
${REAL_USER} ALL=(root) NOPASSWD: ${MV} /tmp/claribot.service /etc/systemd/system/claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${RM} -f /usr/local/bin/claribot
${REAL_USER} ALL=(root) NOPASSWD: ${RM} -f /usr/local/bin/clari
${REAL_USER} ALL=(root) NOPASSWD: ${RM} -f /etc/systemd/system/claribot.service
${REAL_USER} ALL=(root) NOPASSWD: ${JOURNALCTL} -u claribot.service *
EOF

chmod 0440 "$SUDOERS_FILE"

# 문법 검증
if visudo -c -f "$SUDOERS_FILE" > /dev/null 2>&1; then
    echo "sudoers 설정 완료: ${SUDOERS_FILE}"
    echo "사용자: ${REAL_USER}"
    echo ""
    echo "이제 Claude Code 에이전트가 비밀번호 없이 다음을 실행할 수 있습니다:"
    echo "  make install    - 전체 빌드 및 설치"
    echo "  make restart    - 서비스 재시작"
    echo "  make uninstall  - 전체 제거"
    echo ""
    echo "제거하려면: sudo rm ${SUDOERS_FILE}"
else
    echo "Error: sudoers 문법 오류 발생. 파일을 제거합니다."
    rm -f "$SUDOERS_FILE"
    exit 1
fi
